export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import localFont from 'next/font/local';

const customFont = localFont({
  src: '../public/fonts/PPMonumentExtended-Light.ttf',
  weight: '400',
  variable: '--font-custom',
  display: 'swap',
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
